version: "3.9"
services:
  server:
    image: ghcr.io/astral-sh/uv:latest
    working_dir: /app
    volumes:
      - .:/app
    command: uv run --directory server fastapi run --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  web:
    image: node:20
    working_dir: /app/web
    volumes:
      - ./web:/app/web
    command: sh -c "corepack enable && pnpm install && pnpm dev --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - server
