[project]
name = "talesofyours"
version = "0.1.0"
description = "Tales of Yours monorepo"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]",
    "uvicorn",
]

[project.optional-dependencies]
dev = [
    "black",
    "ruff",
    "pre-commit",
]

[tool.black]
line-length = 88

